---
title: "Text as Data Post 1"
description: |
  General outline of my proposed research topic with analysis on feasability and a brief literature review.
author:
  - name: Dana Nestor
    url: https://dnestor.github.io/
    affiliation: UMASS DACSS
    affiliation_url: https://www.umass.edu/sbs/data-analytics-and-computational-social-science-program
date: 02-05-2022
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### Research Questions

#### Background

Management rights clauses are used to strategically reserve certain bargaining positions allowing "exclusive rights to manage, to direct...employees; to evaluate performance, to discipline and discharge employees, to adopt and enforce rules and regulations and policies." Aided by friendly judicial decisions, these clauses are often beyond reach of the National Labor Relations Board (NLRB) and lower court review.  

By claiming certain rights and bargaining to impasse, management is able to immediately implement their last best offer at the expiration of a collective bargaining agreement (CBA). Fighting this is a time consuming and expensive proposition, making this a significant point of leverage in contract negotiations.  

Additionally, courts have relied on empirical analyses of the use of management rights clauses in some of their foundational decisions on this topic (see NLRB v. American National Insurance Co., 343 U.S. 395 (1952)). This opens the door for further analysis to not only improve understanding of the use and spread of these clauses, but even to introduce new evidence that may sway the judiciary towards a new view of the legitimacy of the practice.  

#### Potential Avenues of Exploration

* Map proliferation of specific clauses: how have these clauses spread? Is there a distinguishable network that we can identify from the data?
  + Harness metadata of CBAs to create networks, attach directionality and weights based on identified management rights features to identify probabilities that specific clauses or contract language disseminated via a network or by chance.
* Quantify evolution of clauses: how has the language changed? Can we identify specific trends by sector, industry, size of organization, etc.?
  + Use statistical analysis (machine learning classification models) to quantify the probability that a clause is related to management rights, combine with content/thematic analysis and/or critical discourse analysis to quantify these changes.
  + Establish supervised scaling approach to identify potential latent dimensions of the text and any correlations to networks, industries, etc.
* Compare against history: can we see correlations between changes in language or speed of proliferation against major milestones in the development of labor law and/or union strategy?
  
  
### Data Sources

CBA data is available online for contracts dating all the way back to 1935, 12 years before the Taft-Hartley amendment mandated centralized record keeping. The U.S. Department of Labor Office of Labor-Management Standards (DOL-OLMS) maintains mostly current (though also some historical) records both online and as a Microsoft Access database, including metadata on the bargaining parties, contract dates, employee counts, industry, and links to PDF copies of the full CBA. This dataset is inclusive of both public and private sector CBAs. As of February 5th, 2022, the DOL-OLMS database contained 3,730 entries. 

Additionally, Cornell University's School of Industrial and Labor Relations, Catherwood Library, maintains a historical database on behalf of DOL-OLMS. This is where most pre-1990 CBAs can be found, and it contains similar information to the DOL-OLMS database in terms of metadata and full CBAs. While Cornell is in the process of fully converting those files into machine-readable format, it is unclear what percentage of the collection is currently in this form - this could present a significant issue in data collection. That said, the data set currently contains 2,834 documents dating back to 1935.

Finally, the University of California Berkeley's Institute for Research on Labor and Employment maintains a fully-text-recognized database of union contracts from around the world. However, this data set is the smallest of the three and contains mostly public sector agreements, which differ substantially from the private sector when it comes to management rights clauses due to structural differences in the industry and laws governing these contracts. This database likely will not benefit the project.
  
    
### Literature Review

* Ash, E., MacLeod, W. B., & Naidu, S. (n.d.-a). Optimal Contract Design in the Wild: Rigidity and Control in Collective Bargaining. 46.
  + Analysis of a corpus of 30,000 collective bargaining agreements from Canada from 1986 through 2015. Using ideas and methods from computational linguistics, authors extract measures of rigidity and worker control from the text of the contract clauses. They then analyze how rigidity and authority in contracts varies according to firm-level factors and external factors. This could be used to identify and externally validate the core methodology of this project.
* Ash, E., MacLeod, W. B., & Naidu, S. (n.d.-b). The Language of Contract: Promises and Power in Union Collective Bargaining Agreements. 59.
  + Same authors and data as previous entry
* Rosen, S. Z. (n.d.). Marceau, Drafting a Union Contract. Case Western Reserve Law Review, 6.
  + This handbook provides a perspective on the procedure of drafting a union contract in the 1960s. It could be helpful in identifying changes to procedure over time.
* Ward, M. N. (2004). Contracting participation out of union culture: Patterns of modality and interactional moves in a labour contract settlement / Maurice Norman Ward. [Thesis, The University of Adelaide]. https://digital.library.adelaide.edu.au/dspace/handle/2440/22342
  + This doctoral thesis uses Systemic Functional Linguistics, Critical Discourse Analysis, qualitative, and computational analysis to investigate how language and power interact to construct relationships in the union setting and whether or not union discourse structures promote member participation. While it concentrates on only four documents, the methodologies described here could be useful for latent dimension identification and analysis.
